name: dext
description: A Dart extension library, use to extend dart language, help user to fast build application.
version: 0.1.3
homepage: https://github.com/fluttercandies/dext

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  intl: ">=0.17.0 <1.0.0"
